actionpiece_vocab_size: 40000
activation_function: relu
cache_dir: cache/
category: Sports_and_Outdoors
ckpt_dir: ckpt/
d_ff: 1024
d_kv: 64
d_model: 128
dataset: AmazonReviews2014
dropout_rate: 0.1
epochs: 200
eval_batch_size: 32
eval_interval: 1
feed_forward_proj: relu
log_dir: logs/
lr: 0.005
max_grad_norm: 1.0
max_item_seq_len: 20
metadata: sentence
metrics: '[''ndcg'', ''recall'', ''err'']'
model: ActionPiece
n_hash_buckets: 128
n_inference_ensemble: 5
n_prob_encode_plus: 0
n_threads: 32
num_beams: 50
num_decoder_layers: 4
num_heads: 6
num_layers: 4
num_proc: 1
patience: 20
pq_codebook_size: 256
pq_n_codebooks: 4
rand_seed: 2026
reproducibility: true
run_id: genrec_default
run_local_time: Jul-15-2025_12-59-48
sent_emb_batch_size: 512
sent_emb_dim: 768
sent_emb_model: sentence-transformers/sentence-t5-base
sent_emb_pca: 128
split: leave_one_out
steps: null
tensorboard_log_dir: tensorboard/
topk: '[5, 10, 20, 50]'
train_batch_size: 256
train_shuffle: feature
use_ddp: false
val_metric: ndcg@10
warmup_steps: 10000
weight_decay: 0.15
